// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_i7a9zggHpLXVtDmFYmmy6LUPki9tzic',
    appId: '1:236848410806:web:d5d777facefd755e3c7617',
    messagingSenderId: '236848410806',
    projectId: 'flutter-firebase-e2a43',
    authDomain: 'flutter-firebase-e2a43.firebaseapp.com',
    storageBucket: 'flutter-firebase-e2a43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99Gw8ifUWV-w1q0qp0r31Q9_nb6Tp0jw',
    appId: '1:236848410806:android:648284a17e86d3cb3c7617',
    messagingSenderId: '236848410806',
    projectId: 'flutter-firebase-e2a43',
    storageBucket: 'flutter-firebase-e2a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjA5zOtXMTIPJpTn0dTcVLDdzYw_Unzk',
    appId: '1:236848410806:ios:87c7c86509ac5a7d3c7617',
    messagingSenderId: '236848410806',
    projectId: 'flutter-firebase-e2a43',
    storageBucket: 'flutter-firebase-e2a43.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
